import { createTypes } from 'reduxsauce'

export default createTypes(`

  STATES_FETCH_REQUESTED
  STATES_FETCH_SUCCEEDED
  STATES_FETCH_FAILED

  CITIES_FETCH_REQUESTED
  CITIES_FETCH_SUCCEEDED
  CITIES_FETCH_FAILED

  DEPARTMENTS_FETCH_REQUESTED
  DEPARTMENTS_FETCH_SUCCEEDED
  DEPARTMENTS_FETCH_FAILED

  SELECT_STATE
  SELECT_CITY
  SELECT_DEPARTMENT

  RESET_POSTS
  POSTS_FETCH_REQUESTED
  POSTS_FETCH_SUCCEEDED
  POSTS_FETCH_FAILED

  UPVOTE_POST_REQUESTED
  UPVOTE_POST_SUCCEEDED
  UPVOTE_POST_FAILED

  RESET_ACTIVISTS
  ACTIVISTS_FETCH_REQUESTED
  ACTIVISTS_FETCH_SUCCEEDED
  ACTIVISTS_FETCH_FAILED

  GET_ACTIVISM_PAGE_REQUESTED
  GET_ACTIVISM_PAGE_SUCCEEDED
  GET_ACTIVISM_PAGE_FAILED

  VALIDATE_SIGNUP_INFO_REQUESTED
  VALIDATE_SIGNUP_INFO_SUCCEEDED
  VALIDATE_SIGNUP_INFO_FAILED

  SIGNUP_REQUESTED
  SIGNUP_SUCCEEDED
  SIGNUP_FAILED

  CONFIRM_USER_REQUESTED
  CONFIRM_USER_SUCCEEDED
  CONFIRM_USER_FAILED

  RESEND_CODE_REQUESTED
  RESEND_CODE_SUCCEEDED
  RESEND_CODE_FAILED

  LOGIN_REQUESTED
  LOGIN_SUCCEEDED
  LOGIN_FAILED

  LOGOUT_REQUESTED
  LOGOUT_SUCCEEDED

  RESET_PASSWORD_REQUESTED
  RESET_PASSWORD_REQUEST_SUCCEEDED
  RESET_PASSWORD_REQUEST_FAILED

  CONFIRM_PASSWORD_REQUESTED
  CONFIRM_PASSWORD_SUCCEEDED
  CONFIRM_PASSWORD_FAILED

  GET_SESSION_REQUESTED
  GET_SESSION_SUCCEEDED
  GET_SESSION_FAILED

  RESET_ACCOUNT

  GET_USER_INFORMATION_REQUESTED
  GET_USER_INFORMATION_SUCCEEDED
  GET_USER_INFORMATION_FAILED

  UPLOAD_AVATAR_REQUESTED
  UPLOAD_AVATAR_SUCCEEDED
  UPLOAD_AVATAR_FAILED

  UPDATE_USER_INFORMATION_REQUESTED
  UPDATE_USER_INFORMATION_SUCCEEDED
  UPDATE_USER_INFORMATION_FAILED

  UPLOAD_IMAGE_REQUESTED
  UPLOAD_IMAGE_SUCCEEDED
  UPLOAD_IMAGE_FAILED

  DELETE_IMAGE_REQUESTED
  DELETE_IMAGE_SUCCEEDED
  DELETE_IMAGE_FAILED

  CREATE_ACTIVISM_PAGE_REQUESTED
  CREATE_ACTIVISM_PAGE_SUCCEEDED
  CREATE_ACTIVISM_PAGE_FAILED

  ADD_USER_EMAIL_TO_ACTIVISM_PAGE_REQUESTED
  ADD_USER_EMAIL_TO_ACTIVISM_PAGE_SUCCEEDED
  ADD_USER_EMAIL_TO_ACTIVISM_PAGE_FAILED

  GET_ACTIVISM_PAGE_COMMENTS_REQUESTED
  GET_ACTIVISM_PAGE_COMMENTS_SUCCEEDED
  GET_ACTIVISM_PAGE_COMMENTS_FAILED

  UPVOTE_ACTIVISM_PAGE_REQUESTED
  UPVOTE_ACTIVISM_PAGE_SUCCEEDED
  UPVOTE_ACTIVISM_PAGE_FAILED

  DOWNVOTE_ACTIVISM_PAGE_REQUESTED
  DOWNVOTE_ACTIVISM_PAGE_SUCCEEDED
  DOWNVOTE_ACTIVISM_PAGE_FAILED

  FLAG_ACTIVISM_PAGE_REQUESTED
  FLAG_ACTIVISM_PAGE_SUCCEEDED
  FLAG_ACTIVISM_PAGE_FAILED

  FOLLOW_ACTIVISM_PAGE_REQUESTED
  FOLLOW_ACTIVISM_PAGE_SUCCEEDED
  FOLLOW_ACTIVISM_PAGE_FAILED

  ADD_COMMENT_TO_ACTIVISM_PAGE_REQUESTED
  ADD_COMMENT_TO_ACTIVISM_PAGE_SUCCEEDED
  ADD_COMMENT_TO_ACTIVISM_PAGE_FAILED

  UPVOTE_COMMENT_REQUESTED
  UPVOTE_COMMENT_SUCCEEDED
  UPVOTE_COMMENT_FAILED

  DOWNVOTE_COMMENT_REQUESTED
  DOWNVOTE_COMMENT_SUCCEEDED
  DOWNVOTE_COMMENT_FAILED

  FLAG_COMMENT_REQUESTED
  FLAG_COMMENT_SUCCEEDED
  FLAG_COMMENT_FAILED
`)
